// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkxfewkiblxvszfcgzip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRreGZld2tpYmx4dnN6ZmNnemlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MDA1NzEsImV4cCI6MjA2MTA3NjU3MX0.WSs94YHbwYyg6s2LL4ohuI7ZXE74xNDkA5hOR6nDnQk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);